# Generated by Django 5.2.9 on 2026-01-06 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(default='Sem diagnostico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meus_pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dados_paciente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
