# Generated by Django 5.2.9 on 2026-01-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_paciente_data_consulta_paciente_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELEMEDICINA', 'Telemedicina')], default='PRESENCIAL', max_length=20)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('link_vd', models.URLField(blank=True, null=True)),
                ('receita_digital', models.TextField(blank=True)),
                ('medico', models.ForeignKey(limit_choices_to={'perfil': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='main.paciente')),
            ],
        ),
    ]
