# Generated by Django 5.2.9 on 2026-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_leito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco_da_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='consulta',
            name='link_vd',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
