# Generated by Django 5.2.9 on 2026-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_suprimento_alter_consulta_link_vd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('PACIENTE', 'Paciente'), ('ENFERMEIRO', 'Enfermeiro')], default='PACIENTE', max_length=10),
        ),
    ]
