# Generated by Django 5.2.9 on 2026-01-13 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_enfermeiro_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('PACIENTE', 'Paciente'), ('ENFERMEIRO', 'Enfermeiro'), ('PENDENTE', 'Pendente')], default='PACIENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_designado', models.CharField(default='Recepção principal', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_secretaria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
