# Generated by Django 5.2.9 on 2026-01-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_usuario_perfil_secretaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('PENDENTE', 'pendente')], default='AGENDADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('PACIENTE', 'Paciente'), ('ENFERMEIRO', 'Enfermeiro'), ('SECRETARIA', 'Secretaria')], default='PACIENTE', max_length=10),
        ),
    ]
