# Generated by Django 5.2.9 on 2026-01-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_consulta_status_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='secretaria_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.secretaria'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('PENDENTE', 'pendente')], default='PENDENTE', max_length=20),
        ),
    ]
